Added BT env for HWC-API
Be-Secure/besecure-ce-env-repo pull request #19
Opened 2023-09-05 04:21 UTC by sudhirverma

2023-09-05 06:25 UTC, pramit-d requested changes

2023-09-05 06:25 UTC, pramit-d commented on hwc_api/0.0.1/besman-hwc_api-BT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-bes-java:Be-Secure/ansible-role-oah-maven:Be-Secure/ansible-role-oah-eclipse
@sudhirverma Only java is installing, maven & eclipse are not. 
use '**,**' instead of '**:**'

2023-10-10 02:59 UTC, sudhirverma commented on hwc_api/0.0.1/besman-hwc_api-BT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-bes-java:Be-Secure/ansible-role-oah-maven:Be-Secure/ansible-role-oah-eclipse
done

2023-10-10 06:35 UTC, asa1997 approved these changes
@sudhirverma LGTM

2023-10-10 06:35 UTC, merged