added BT & RT env for newrelic-java-agent
Be-Secure/besecure-ce-env-repo pull request #20
Opened 2024-01-29 03:36 UTC by NeerajK007

added BT & RT env for newrelic-java-agent

2024-01-29 08:52 UTC, asa1997 commented on newrelic/0.0.1/besman-newrelic-java-agent-BT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-bes-java
We need a package manager as well as an ide.

2024-01-29 08:52 UTC, asa1997 commented on newrelic/0.0.1/besman-newrelic-java-agent-RT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-bes-java
Add a package manager and an ide.

2024-01-29 08:52 UTC, asa1997 requested changes
@NeerajK007 Please look at the comments.

2024-02-22 03:38 UTC, NeerajK007 commented
Closing this as suggested feedback is incorporated in another pull request

2024-02-22 03:38 UTC, closed without merging