opencti BT & RT env updated
Be-Secure/besecure-ce-env-repo pull request #23
Opened 2024-03-04 12:56 UTC by NeerajK007

opencti BT & RT env updated with : 
install function
uninstall function
validate function

2024-03-20 10:57 UTC, pramit-d requested changes
@NeerajK007 env installation failing.

![Screenshot from 2024-03-20 16-24-14](https://github.com/Be-Secure/besecure-ce-env-repo/assets/125947785/cba0b3a8-38b9-488f-8aee-a72e66b46707)

2024-04-03 05:22 UTC, asa1997 requested changes
@NeerajK007 Please update the env scripts to the latest format.

2024-04-05 05:05 UTC, asa1997 commented on newrelic/0.0.1/besman-newrelic-java-agent-BT-env-config.yaml
@NeerajK007 This file is still in the old format

2024-04-05 05:05 UTC, asa1997 commented on newrelic/0.0.1/besman-newrelic-java-agent-BT-env.sh
@NeerajK007 Please update this file

2024-04-08 06:48 UTC, asa1997 commented on opencti/0.0.1/besman-opencti-RT-env.sh
> +function __besman_uninstall {
You should uninstall/update/reset/validate everything that was installed.

2024-04-08 06:49 UTC, asa1997 requested changes
@NeerajK007 Please address the comments

2024-04-12 03:57 UTC, NeerajK007 commented on opencti/0.0.1/besman-opencti-RT-env.sh
> +function __besman_uninstall {
Hi Arun,
Uninstall and validate functions are done.
I don't know what will go in reset and update function ??

2024-04-12 14:07 UTC, asa1997 commented
@NeerajK007 Please resolve the conflicts

2024-04-22 03:46 UTC, asa1997 approved these changes
@NeerajK007 LGTM

2024-04-22 03:46 UTC, merged