Uploading Environment for jackson-core
Be-Secure/besecure-ce-env-repo pull request #33
Opened 2024-04-23 12:56 UTC by Aditi8007

2024-04-24 03:08 UTC, asa1997 commented on jackson-core/0.0.1/besman-jackson-core-BT-env-config.yaml
> +BESMAN_ARTIFACT_TYPE: # project/ml model/training dataset #***
Should be project

2024-04-24 03:08 UTC, asa1997 commented on jackson-core/0.0.1/besman-jackson-core-BT-env-config.yaml
> +BESMAN_ARTIFACT_VERSION: #Enter the version of the artifact here. #***
Should add the version under assessment.

2024-04-24 03:09 UTC, asa1997 requested changes
@Aditi8007 Please address the requested changes.

2024-04-24 04:00 UTC, Aditi8007 commented
Now please check

2024-04-24 04:21 UTC, asa1997 commented on list.txt
> +Be-Secure/besecure-ce-env-repo/druid-BT-env,0.0.1
Please remove this

2024-04-24 04:21 UTC, asa1997 requested changes
@Aditi8007 You have an additional entry into the list file

2024-04-25 04:25 UTC, asa1997 approved these changes
@Aditi8007 LGTM.

2024-04-25 04:25 UTC, merged