Added BeSman ML assessment environment
Be-Secure/besecure-ce-env-repo pull request #41
Opened 2024-05-23 12:13 UTC by pramit-d

https://github.com/Be-Secure/besecure-ce-env-repo/issues/40

CounterFit installation and uninstallation script is added.

2024-05-24 05:36 UTC, asa1997 requested changes

2024-05-24 05:36 UTC, asa1997 commented on ml_assessment/0.0.1/besman-ml_assessment-env-config.yaml
> +BESMAN_ARTIFACT_TYPE: # project/ml model/training dataset #***
Should be ml model

2024-05-24 05:36 UTC, asa1997 commented on ml_assessment/0.0.1/besman-ml_assessment-env-config.yaml
> +BESMAN_ARTIFACT_NAME: ml_assessment-env #***
Should be the name of the artifact under test. Should be empty for now.

2024-05-24 05:36 UTC, asa1997 commented on ml_assessment/0.0.1/besman-ml_assessment-env-config.yaml
> +BESMAN_ENV_NAME: ml_assessment-env #***
Should this be ml_assessment-env or ml_RT-env? Please confirm.

2024-05-24 09:38 UTC, pramit-d commented on ml_assessment/0.0.1/besman-ml_assessment-env-config.yaml
> +BESMAN_ARTIFACT_TYPE: # project/ml model/training dataset #***
Done

2024-05-24 09:38 UTC, pramit-d commented on ml_assessment/0.0.1/besman-ml_assessment-env-config.yaml
> +BESMAN_ARTIFACT_NAME: ml_assessment-env #***
Updated.

2024-05-24 09:38 UTC, pramit-d commented on ml_assessment/0.0.1/besman-ml_assessment-env-config.yaml
> +BESMAN_ENV_NAME: ml_assessment-env #***
Updated the BeSman env name to 'ML-RT-env'

2024-05-27 04:16 UTC, asa1997 approved these changes
@pramit-d LGTM

2024-05-27 04:16 UTC, merged