80% completed reday to Review . Ignore the comented line
Be-Secure/besecure-ce-env-repo pull request #57
Opened 2024-06-20 15:27 UTC by samirparhi-dev

80% completed reday to Review . Ignore the comented line. Please Review Accordingly.

FYI : @sand-hya @Aditi8007 @sumodgeorge @panickervinod

2024-06-21 03:54 UTC, samirparhi-dev commented
Please Check for the Function and syntax of naming conventionand reusability and provide me the the Feedback.

What Should be reviewed ?

1. Gitignore : Can be reviewed and Merged.
2. `kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml`  : Can be reviewed and merged.
3. kubernetes/0.0.1/besman-kubernetes-RT-env.sh :
         function __besman_install
               -  detect_container_runtime(): Can be reviewed and tested
               - install_container_runtime() : Can be reviewed and tested 
               - check_and_install_python_pip() : Can be reviewed and tested
               - preparing_sonar_qube() : Can be reviewed and tested
               - preparing_fosology(): Can be reviewed and tested
               - container_tool_setup() : Can be reviewed and tested


What is pending? 


1. Under function __besman_install 
    * Setting Up Go Lang
    * Setting up snyk
    * Setting Up Criticality Score
5. Under function __besman_uninstall
    1. stop_containers()
    2. remove_containers()
    6. purge_containers()
    7. uninstall_container()
3. function __besman_validate
    1. Validate the required tool
However it is already there in install steps , just review and let me know from there which can be move to this function else I will write it fresh
5. function __besman_reset
        1. Reset the tool

2024-06-21 04:24 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-oah-maven #add the roles here. format - <Github id>/<repo name>,<Github id>/<repo name>,<Github id>/<repo name>,... #***
@samirparhi-dev Is maven required for this project?

2024-06-21 09:09 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-oah-maven #add the roles here. format - <Github id>/<repo name>,<Github id>/<repo name>,<Github id>/<repo name>,... #***
Nope :-)

2024-06-21 09:14 UTC, asa1997 requested changes
Please also update the list.txt file.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-oah-maven #add the roles here. format - <Github id>/<repo name>,<Github id>/<repo name>,<Github id>/<repo name>,... #***
Please comment this as you you are not using ansible.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH: $BESMAN_DIR/tmp/$BESMAN_ARTIFACT_NAME #***
Please comment this as you are not using ansible.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_ARTIFACT_TRIGGER_PLAYBOOK: besman-$BESMAN_ARTIFACT_NAME-RT-trigger-playbook.yaml #***
Please comment this as you are not using ansible.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_DISPLAY_SKIPPED_ANSIBLE_HOSTS: false #***
Please comment this as you are not using ansible.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_ANSIBLE_ROLES_PATH: $BESMAN_DIR/tmp/$BESMAN_ARTIFACT_NAME/roles #***
Please comment this as you are not using ansible.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_check_for_ansible || return 1 # Checks if ansible is installed or not.
You dont need this function as you are not using ansible roles

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_create_roles_config_file      # Creates the role config file with the parameters from env config
You dont need this function as you are not using ansible roles

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_update_requirements_file
You dont need this function as you are not using ansible roles

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_ansible_galaxy_install_roles_from_requirements # Downloads the ansible roles mentioned in BESMAN_ANSIBLE_ROLES to BESMAN_ANSIBLE_ROLES_PATH
You dont need this function as you are not using ansible roles

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_check_for_trigger_playbook "$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH/$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK"
You dont need this function as you are not using ansible roles

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    [[ "$?" -eq 1 ]] && __besman_create_ansible_playbook # Creates the trigger playbook if not present.
You dont need this function as you are not using ansible roles

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_run_ansible_playbook_extra_vars "$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH/$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK" "bes_command=install role_path=$BESMAN_ANSIBLE_ROLES_PATH" || return 1
You dont need this function as you are not using ansible roles

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    detect_container_runtime() {
Please refrain from writing functions inside another function. You can call this function from install.

Also please follow the format `function __besman_<rest of fun name>()`

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +                echo -e "\n PODMAN Detected. "
Please use __besman_echo calls instead of direct echo if you wish to highlight the output messages. Refer - https://github.com/Be-Secure/BeSman/blob/master/src/main/bash/besman-utils.sh

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    install_container_runtime() {
Format check for function

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    preparing_sonar_qube(){
Please move the function definitions outside install function wherever applicable.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    container_tool_setup sonarqube 9000 9000
Try making the ports configurable. Use the config file. All variables in the config file starting with `BESMAN_` will be made into environment variables during execution. You can use this functionality make it user configurable.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +        container_tool_setup fosology 8081 80
Try making the ports configurable. Use the config file. All variables in the config file starting with `BESMAN_` will be made into environment variables during execution. You can use this functionality make it user configurable.

2024-06-21 09:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    # go is required to install criticality_score
You can use ansible role to install criticality_score

2024-06-21 09:35 UTC, samirparhi-dev commented
If I do not want to Use ansible roles , In which file, I can write the install function?

2024-06-21 09:36 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +        container_tool_setup fosology 8081 80
👍🏼

2024-06-21 09:36 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    container_tool_setup sonarqube 9000 9000
👍🏼

2024-06-21 09:37 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    preparing_sonar_qube(){
Can you please elaborate this , Where can I write these function ? In this file itself or should I write it in any other place? lets say for this function `preparing_sonar_qube()` , where should I write it ?

2024-06-21 09:47 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    install_container_runtime() {
Can you please explain this ?

2024-06-21 09:49 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    container_tool_setup sonarqube 9000 9000
Ports are not variable but standards specific to any tool, Should this to be hard coded or part of configuration file ?

2024-06-21 09:49 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +        container_tool_setup fosology 8081 80
Ports are not variable but standards specific to any tool, Should this to be hard coded or part of configuration file ?

2024-06-21 09:50 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    # go is required to install criticality_score
As, I do not want to use ansible role, please let me know where can I write it .

2024-06-25 04:11 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    install_container_runtime() {
please follow the format function __besman_<rest of fun name>(). Refer [this](https://github.com/Be-Secure/besecure-ce-env-repo/blob/master/checklist.md)

2024-06-25 04:14 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    preparing_sonar_qube(){
You can write it in the same file, but move the function definition outside `__besman_install()`. You can call these functions inside `install()`.

2024-06-25 04:15 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    container_tool_setup sonarqube 9000 9000
Better to be part of configuration. You can also provide comments in the config file next to the variable which explains what this variable is and the standard value.

2024-06-25 04:15 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +        container_tool_setup fosology 8081 80
See above comment.

2024-06-25 04:16 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    # go is required to install criticality_score
Install the env script itself. Function definition should be outside other function definitions.

2024-06-25 04:17 UTC, asa1997 commented
> If I do not want to Use ansible roles , In which file, I can write the install function?

You can use the env file itself.

2024-06-25 09:17 UTC, asa1997 commented
@samirparhi-dev Please raise your prs to the develop branch of the repo.

2024-06-26 04:11 UTC, samirparhi-dev commented
@asa1997 : Can you check the recent commit and let me know if things are organised the way  it should be

2024-06-26 04:20 UTC, asa1997 requested changes
@samirparhi-dev 
- You have few more ansible related function calls inside uninstall,validate and reset. 
- Any reason why you are giving a function definition inside another function definition? Please let me know.
- Also, please raise this pr to the develop branch as we have adopted a new branching strategy. See contributor's guide.

2024-06-26 04:20 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_create_roles_config_file      # Creates the role config file with the parameters from env config
Please remove it

2024-06-26 04:20 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_check_for_trigger_playbook "$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH/$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK"
Remove all the ansible related function calls from other functions.

2024-06-26 04:20 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_check_for_trigger_playbook "$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH/$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK"
Remove ansible related function calls.

2024-06-26 04:20 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_check_for_trigger_playbook "$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH/$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK"
Remove ansible related function calls.

2024-06-26 04:20 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_check_for_trigger_playbook "$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH/$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK"
Remove ansible related function calls.

2024-06-26 04:20 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +            __besman_install_podman_linux() {
Any reason why you are writing a function definition inside another function definition?

2024-08-30 04:54 UTC, asa1997 requested changes
@samirparhi-dev  Please address the comments.

<ins>**Also please raise your pr to `dev` branch.**</ins>

2024-08-30 04:54 UTC, asa1997 commented on .vscode/settings.json
Use .gitignore for this file.

2024-08-30 04:54 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_PRIVATE_IMAGE_REPO: ""
Should this be empty?

2024-08-30 04:54 UTC, asa1997 commented on kubernetes/0.0.1/test.yml
This config has been added into env-config. So please remove.

2024-09-01 11:52 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_check_for_trigger_playbook "$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH/$BESMAN_ARTIFACT_TRIGGER_PLAYBOOK"
done

2024-09-01 12:12 UTC, closed without merging