Adding RT env
Be-Secure/besecure-ce-env-repo pull request #74
Opened 2024-07-14 13:36 UTC by sand-hya

logstash: https://github.com/Be-Secure/Be-Secure/issues/235
prometheus: https://github.com/Be-Secure/Be-Secure/issues/299
privacyidea: https://github.com/Be-Secure/Be-Secure/issues/377

2024-07-16 04:51 UTC, asa1997 requested changes
@sand-hya Please resolve the conflicts

2024-07-16 04:51 UTC, asa1997 commented on logstash/0.0.1/besman-logstash-RT-env-config.yaml
> +ASSESSMENT_STEP:
You can remove this.

2024-07-16 04:51 UTC, asa1997 commented on logstash/0.0.1/besman-logstash-RT-env.sh
> +    validate_environment() {
What is the use of this functions? Also, please provide this function definition outside other functions.

2024-07-16 04:51 UTC, asa1997 commented on privacyidea/0.0.1/besman-privacyidea-RT-env-config.yaml
> +BESMAN_ARTIFACT_TYPE: # project/ml model/training dataset #***
missing parameter - `project`

2024-07-16 04:51 UTC, asa1997 commented on privacyidea/0.0.1/besman-privacyidea-RT-env-config.yaml
> +BESMAN_ARTIFACT_VERSION: #Enter the version of the artifact here. #***
missing parameter

2024-07-16 04:51 UTC, asa1997 commented on privacyidea/0.0.1/besman-privacyidea-RT-env-config.yaml
> +ASSESSMENT_STEP:
please remove this.

2024-07-16 04:51 UTC, asa1997 commented on privacyidea/0.0.1/besman-privacyidea-RT-env.sh
> +    validate_python() {
Please move this func definition outside

2024-07-16 04:51 UTC, asa1997 commented on prometheus/0.0.1/besman-prometheus-RT-env-config.yaml
> +BESMAN_ARTIFACT_TYPE: # project/ml model/training dataset #***
missing parameter

2024-07-16 04:51 UTC, asa1997 commented on prometheus/0.0.1/besman-prometheus-RT-env-config.yaml
> +BESMAN_ARTIFACT_VERSION: #Enter the version of the artifact here. #***
missing parameter

2024-07-16 04:51 UTC, asa1997 commented on prometheus/0.0.1/besman-prometheus-RT-env-config.yaml
> +ASSESSMENT_STEP:
please remove this.

2024-07-16 04:51 UTC, asa1997 commented on prometheus/0.0.1/besman-prometheus-RT-env.sh
> +    uninstall_go() {
you can add the code in this function itself. If you want to separate the functions then move this outside other functions.

2024-07-16 04:51 UTC, asa1997 commented on prometheus/0.0.1/besman-prometheus-RT-env.sh
> +    validate_environment() {
move this outside other function definitions.

2024-07-16 04:51 UTC, asa1997 commented on logstash/0.0.1/besman-logstash-RT-env-config.yaml
> +BESMAN_ARTIFACT_TYPE: # project/ml model/training dataset #***
missing parameter

2024-07-16 04:51 UTC, asa1997 commented on logstash/0.0.1/besman-logstash-RT-env-config.yaml
> +BESMAN_ARTIFACT_VERSION: #Enter the version of the artifact here. #***
missing parameter

2024-07-16 06:40 UTC, sand-hya commented
Hi @asa1997, performed the changes requested and resolved the conflicts

2024-07-23 04:04 UTC, asa1997 requested changes
@sand-hya Please resolve the conflicts. Also please provide the names of the env on the title

2024-07-23 06:53 UTC, closed without merging