Uploading RT ENV for Open-Vehicle-Monitoring-System-3 ,SmartEVSE-3 ,busmaster & open_evse
Be-Secure/besecure-ce-env-repo pull request #90
Opened 2024-08-21 11:18 UTC by Aditi8007

#Open-Vehicle-Monitoring-System-3 
#SmartEVSE-3 
#busmaster 
#open_evse

2024-09-13 12:22 UTC, pramit-d requested changes
@Aditi8007 , **`TASK [ansible-role-oah-sonarQube: check if Docker is installed]`** is failing in all of the env scripts. Please check the issue.![PXL_20240913_122635898.MP~2.jpg](https://github.com/user-attachments/assets/a8de123d-ecfd-4179-afc2-90f62222e261)

2024-09-13 12:22 UTC, pramit-d commented on environment-metadata.json
> +            },
@Aditi8007 , please change author name and type to BeSLab and Lab.

```
"author": {
    "name": "BeSLab",
    "type": "Lab"
}

2024-09-13 12:22 UTC, pramit-d commented on environment-metadata.json
> +            },
@Aditi8007 , please change author name and type to BeSLab and Lab.

```
"author": {
    "name": "BeSLab",
    "type": "Lab"
}

2024-09-13 12:22 UTC, pramit-d commented on environment-metadata.json
> +            },
@Aditi8007 , please change author name and type to BeSLab and Lab.

```
"author": {
    "name": "BeSLab",
    "type": "Lab"
}

2024-09-13 12:22 UTC, pramit-d commented on environment-metadata.json
> +            },
@Aditi8007 , please change author name and type to BeSLab and Lab.

```
"author": {
    "name": "BeSLab",
    "type": "Lab"
}

2024-09-16 09:35 UTC, Aditi8007 commented on environment-metadata.json
> +            },
@pramit-d 
TASK [ansible-role-oah-sonarQube: check if Docker is installed] is working for in all of the env scripts.
unable attach Screenshot here so I sent on teams please check

2024-11-15 08:26 UTC, merged