Env for K8s
Be-Secure/besecure-ce-env-repo pull request #94
Opened 2024-09-09 11:38 UTC by samirparhi-dev

FYI @asa1997 @harimohanr @panickervinod @sumodgeorge

2024-09-11 09:40 UTC, pramit-d requested changes
Hi @samirparhi-dev, please update environment-metadata.json and list.txt files. Without updating list.txt, the env will not be available in the env list.

2024-09-11 10:21 UTC, samirparhi-dev commented
> Hi @samirparhi-dev, please update environment-metadata.json and list.txt files. Without updating list.txt, the env will not be available in the env list.

done

2024-09-11 10:57 UTC, pramit-d commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_SYSTEM_CURRENT_STATE:
@samirparhi-dev , **BESMAN_SYSTEM_CURRENT_STATE** should not be empty, otherwise BeSman will throw error.

2024-09-11 11:01 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +  yq:
@pramit-d: My whole logic consider the configfile as `.yml` and I used `.yml` parser . `.yml` should be treated like `yml` not `.txt` right ?  

 @harimohanr @panickervinod @asa1997 May I know why the design is way?

> @samirparhi-dev , this kind of yaml structure is not supported by BeSman. @asa1997 was using cut command internally to fetch the besman env variables and values. As per the logic **BESMAN_REQUIRED_TOOL_SET** is empty, and BeSman will throw error if any env variable is empty at the time of running the script. **BESMAN_REQUIRED_TOOL_SET** and **BESMAN_REQUIRED_TOOL_SET** must have some values.
> 
> ex:
> 
> ```
> BESMAN_REQUIRED_TOOL_SET: <values>
> ```

@pramit-d: My whole logic consider the configfile as `.yml` and I used `.yml` parser . `.yml` should be treated like `yml` not `.txt` right ?  

 @harimohanr @panickervinod @asa1997 May I know why the design is way?

2024-09-11 11:03 UTC, samirparhi-dev commented on kubernetes/0.0.1/besman-kubernetes-RT-env-config.yaml
> +BESMAN_SYSTEM_CURRENT_STATE:
> @samirparhi-dev , **BESMAN_SYSTEM_CURRENT_STATE** should not be empty, otherwise BeSman will throw error.

@pramit-d: My whole logic consider the configfile as `.yml` and I used `.yml` parser . `.yml` should be treated like `yml` not `.txt` right ?  

 @harimohanr @panickervinod @asa1997 May I know why the design is way?

2024-09-13 07:26 UTC, samirparhi-dev commented
As per the Discussion with Arun, Currently I have bypassed the Variable name and commited. We will later enhance the besman tool to handle is automatically . @pramit-d: Do test and let me know if all are working or anything breaking FYI @bananth2008

2024-09-13 10:01 UTC, pramit-d requested changes

2024-09-13 10:01 UTC, pramit-d commented on environment-metadata.json
> +            "name": "k8s-RT-env",
@samirparhi-dev , env name present in environment-metadata.json is different with the env name in list.txt, config and script file. Please use only same env name everywhere.

2024-10-03 04:58 UTC, asa1997 requested changes

2024-10-03 04:58 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    __besman_install_tools yq "" "" "" "" || return 1
@samirparhi-dev Where is the definition for this function call?

2024-10-03 04:58 UTC, asa1997 commented on kubernetes/0.0.1/besman-kubernetes-RT-env.sh
> +    export BESMAN_K8S_CONFIG_FILE_PATH="./$BESMAN_ARTIFACT_NAME/$BESMAN_ARTIFACT_VERSION/besman-kubernetes-RT-env-config.yaml"
The config file is expected to be in the `$HOME` dir. Please explain the use of this variable.

2024-11-15 06:11 UTC, merged