added env for cilium
Be-Secure/besecure-ce-env-repo pull request #97
Opened 2024-09-09 11:41 UTC by samirparhi-dev

FYI @panickervinod @harimohanr @sumodgeorge @asa1997

2024-09-11 09:42 UTC, pramit-d requested changes
Hi @samirparhi-dev, please update environment-metadata.json and list.txt files. Without updating list.txt, the env will not be available in the env list.

2024-09-11 10:19 UTC, samirparhi-dev commented
> Hi @samirparhi-dev, please update environment-metadata.json and list.txt files. Without updating list.txt, the env will not be available in the env list.

@pramit-d :done

2024-09-11 10:53 UTC, pramit-d submitted a review, later dismissed

2024-09-11 10:53 UTC, pramit-d commented on cilium/0.0.1/besman-cilium-RT-env-config.yaml
> +BESMAN_REQUIRED_TOOL_SET:
@samirparhi-dev , this kind of yaml structure is not supported by BeSman. @asa1997 was using cut command internally to fetch the besman env variables and values. As per the logic **BESMAN_REQUIRED_TOOL_SET** is empty, and BeSman will throw error if any env variable is empty at the time of running the script. **BESMAN_REQUIRED_TOOL_SET** and **BESMAN_REQUIRED_TOOL_SET** must have some values.

ex:
```
BESMAN_REQUIRED_TOOL_SET: <values>

2024-09-11 10:53 UTC, pramit-d commented on cilium/0.0.1/besman-cilium-RT-env-config.yaml
> +BESMAN_SYSTEM_CURRENT_STATE:
@samirparhi-dev , BESMAN_SYSTEM_CURRENT_STATE should not be empty, otherwise BeSman will throw error.

2024-09-11 11:04 UTC, samirparhi-dev commented on cilium/0.0.1/besman-cilium-RT-env-config.yaml
> +BESMAN_REQUIRED_TOOL_SET:
> @samirparhi-dev , this kind of yaml structure is not supported by BeSman. @asa1997 was using cut command internally to fetch the besman env variables and values. As per the logic **BESMAN_REQUIRED_TOOL_SET** is empty, and BeSman will throw error if any env variable is empty at the time of running the script. **BESMAN_REQUIRED_TOOL_SET** and **BESMAN_REQUIRED_TOOL_SET** must have some values.
> 
> ex:
> 
> ```
> BESMAN_REQUIRED_TOOL_SET: <values>
> ```

@pramit-d: My whole logic consider the configfile as `.yml` and I used `.yml` parser . `.yml` should be treated like `yml` not `.txt` right ?  

 @harimohanr @panickervinod @asa1997 May I know why the design is way?

2024-09-11 11:04 UTC, samirparhi-dev commented on cilium/0.0.1/besman-cilium-RT-env-config.yaml
> +BESMAN_SYSTEM_CURRENT_STATE:
> @samirparhi-dev , BESMAN_SYSTEM_CURRENT_STATE should not be empty, otherwise BeSman will throw error.

@pramit-d: My whole logic consider the configfile as `.yml` and I used `.yml` parser . `.yml` should be treated like `yml` not `.txt` right ?  

 @harimohanr @panickervinod @asa1997 May I know why the design is way?

2024-09-13 07:25 UTC, samirparhi-dev commented
As per the Discussion with Arun, Currently I have bypassed the Variable name and commited. We will later enhance the besman tool to handle is automatically . @pramit-d: Do test and let me know if all are working or anything breaking FYI @bananth2008

2024-11-15 05:50 UTC, anilsingla approved these changes

2024-11-15 05:58 UTC, merged